### PR TITLE
feat: Fix error handling logic for fetching tariffs

### PR DESCRIPTION
**Pull request by LukasStrickler**
Modify InitialSignUpControllerStep3 and InitialSignUpControllerStep2 to handle
exceptional cases when fetching gas and heating tariffs. Show a refresh popup
with an error message in case the data is not fetched successfully. Update FXML
paths in InitialSignUpControllerStep2 to load the correct FXML file. Add Stage
parameter to FXMLUtility constructor for proper initialization. Update bundle
properties with a new error message for signup errors.

solves #101

### CODE REVIEW

**Comment by joscha-st** [comment]
Thank you, this solves the #101  issue. For the future we could aim to implement this differently, so there is no unnecessary request when going to the next step, e.g. by offering the reload on the next page.

image

**Review by joscha-st — CHANGES_REQUESTED** [review]
Are you sure that it is correct to have whole language bundle reformatted?

**Comment by LukasStrickler** [comment]
was done by auto formatting

**Comment by LukasStrickler** [comment]
> Thank you, this solves the #101 issue. For the future we could aim to implement this differently, so there is no unnecessary request when going to the next step, e.g. by offering the reload on the next page.
> 
> image

the page only loads once the data has been fetched
it is implementable like that but a popup is a smoother DX/UX, as otherwise we would "break" apart the signup process and is consistent with all other error handling being in popups

**Review by joscha-st — APPROVED** [review]

**Pull request merged**
