### PR TITLE
BPMN with Business Logic

### PR DESCRIPTION
**Pull request by TrustedSamu**

### CODE REVIEW

**Review by joscha-st — CHANGES_REQUESTED** [review]
1. "Datenbank" should be "server" or other
2. Business Logic lane should be in between UI and Server 
3. There cannot be any UI to server connection directly, must always go through business logic

**Comment by joscha-st** [comment]
also pls add a description for this ;)

**Comment by TrustedSamu** [comment]
done

**Comment by joscha-st** [comment]
@TrustedSamu @baghdadbaecker I just saw, that for the different processes there is still some inconsistency. I think we should always have "Server" as counterpart to "UI" and at some point we have "Stadtwerke ERP", this seems inconvivient

**Comment by TrustedSamu** [comment]
Should be fixed now as Leo has the others in his branch. Please accept pull requested

**Review by joscha-st — APPROVED** [review]
thx, looks good now

**Pull request merged**
